Import('env')

env['lib_includes'] += Glob('*.[hi]pp')
env['lib_sources'] += Glob('*.cpp')

SConscript('boostextensions/SConscript')
SConscript('srreal/SConscript')
SConscript('SConscript.version')

# vim: ft=python
