Import('env')

def srcsupported(f):
    rv = env.get('has_objcryst') or 'objcryst' not in str(f).lower()
    return rv

env['lib_includes'] += filter(srcsupported, Glob('*.[hi]pp'))
env['lib_sources'] += filter(srcsupported, Glob('*.cpp'))

# vim: ft=python
