{% set setupdata = load_setup_py_data(from_recipe_dir=True) %}

package:
  name: libdiffpy
  version: {{ setupdata['version'] }}

source:
  # git_url: https://github.com/diffpy/libdiffpy.git
  git_url: ..

build:
  number: 0

requirements:
  build:
    - scons
    - boost 1.61.0
    - gsl 2.1
    - libobjcryst 2015.1|2015.1.*

  run:
    - boost 1.61.0
    - gsl >=2.1
    - libobjcryst 2015.1|2015.1.*

test:
  requires:
    - cxxtest
    - scons

  source_files:
    - SConstruct
    - site_scons/
    - src/SConscript
    - src/SConscript.configure
    - src/tests/

  # commands:
    # Execute the run_test.sh script.

about:
  home: https://github.com/diffpy/libdiffpy
  summary: C++ calculators of PDF, bond valence sum and other pair quantities.
  license: Modified BSD License
  license_file: LICENSE.txt

# See http://docs.continuum.io/conda/build.html
# for more information about meta.yaml.
